### PR TITLE
Response to XML

### PR DESCRIPTION
**Pull request by theDisco**
Hi,

for debugging and logging purposes I was missing an option to dump the raw response from ebay. I have added a new method to the BaseType to allow dumping the responses as well. I have also extended the unit tests to include the new option.

Best

### CODE REVIEW

**Comment by davidtsadler** [comment]
Thanks for the pull request I'll look at merging it over the weekend. There are a few things that I want to do differently with regards this feature so there will be some changes to the code.

**Comment by theDisco** [comment]
This solution works, but is not perfect for two reasons. First of all
everything is a BaseType and I think you should favor composition over
inheritance. I was confused when I got a warning when I tried to call
toRequestXml on response object.

After implementing the toResponseXml I was also confused, why the resulting
XML was invalid. It seems that entities are not correctly handled by the
parser. Are you going to address this problems in the next releases?

**Comment by davidtsadler** [comment]
I would like to look into the entities issue some more. Can you give me a copy of the XML that is returned from eBay and the XML that is generated by `toRequestXml`.  I would like to see the difference between the two.

To get the XML that eBay returns you can attach a logger to the service and pass `true` to the `debug` configuration option. 

```php
<?php
require __DIR__.'vendor/autoload.php';

use \DTS\eBaySDK\Constants;
use \DTS\eBaySDK\Trading\Services;
use \DTS\eBaySDK\Trading\Types;

class EchoLogger extends Psr\Log\AbstractLogger 
{
    public function log($level, $message, array $context = array())
    {
        if ($message === 'Response') {
            echo "RAW eBay Response\n\n".$context['body']."\n\n";
        } 
    }
}

$service = new Services\TradingService(array(
    'apiVersion' => '903',
    'siteId' => Constants\SiteIds::US,
    'authToken' => <YOUR AUTH TOKEN>
    'debug' => true
));

$service->logger(new EchoLogger());

$request = new Types\GeteBayOfficialTimeRequestType();

$response = $service->geteBayOfficialTime($request);
echo "toResponseXml\n\n".$response->toResponseXml()."\n\n";
```

The SDK allows you to attach a class that implements the [Psr\Log\LoggerInterface](https://github.com/php-fig/log) interface. As long as the `debug` configuration option is true [requests](https://github.com/davidtsadler/ebay-sdk/blob/master/src/DTS/eBaySDK/Services/BaseService.php#L341) and [responses](https://github.com/davidtsadler/ebay-sdk/blob/master/src/DTS/eBaySDK/Services/BaseService.php#L358) are sent to the attached logger. I have to apologise as I have yet to write any documentation for this feature so it's not that well known.

**Comment by theDisco** [comment]
I missed the logger option, I will take a look at it tomorrow.

Regarding the entities problem please take a look at the examples repository provided by you. First try to add an item using [AddItem type](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/03-add-auction-item.php). First of all I think it would be nice if the parser would do the correct conversion of entities. Look at this:

```
$item->Title = 'Bits &amp; Bobs';
$item->Description = '&lt;H1&gt;Bits &amp; Bobs&lt;/H1&gt;&lt;p&gt;Just some stuff I found.&lt;/p&gt;';
```

In my opinion, consumer should not be concerned about the correct encoding. What if the parser changes and it will provide conversion after all? You should provide a consistent interface between consumer and service.

If you request the created item using GetItem request, part of the response will be the title. If you use `toResponseXml` you will get following xml:

 ```
...
<Title>Bits & Bobs</Title>
...
```

If you try to pretty print it using following code:

```
$dom = dom_import_simplexml($simpleXml)->ownerDocument;
$dom->formatOutput = true;
echo $dom->saveXML();
```

You will get a warning about incorrect xml.

If you need more information about the problem, let me know

**Comment by davidtsadler** [comment]
The issue as to whether the SDK should automatically convert strings to CDATA or entities [has been raised before](https://github.com/davidtsadler/ebay-sdk-trading/issues/5). Basically it's up to client code to pass the correct strings to use in the XML. The SDK just uses the value as is when creating the XML.

Looking at the issue is seems that eBay is returning the following correct XML

``
<Title>Bits &amp; Bobs</Title>
```

What is going wrong is that when the SDK assigns the value of this element to the Title property of the object it is been converted in to the string `Bits & Bobs`.  Because the SDK does not escape or convert strings into entities this will result in invalid XML later on. 

The issue is going to be due to [XmlParser](https://github.com/davidtsadler/ebay-sdk/blob/master/src/DTS/eBaySDK/Parser/XmlParser.php) as that is responsible for converting XML into PHP objects. I'll take a look and see how to fix it.

**Pull request closed without merging**
